#!/bin/sh

[ -n "$(ls /etc/pre_install)" ] && opkg install /etc/pre_install/*.ipk --force-depends
rm -rf /etc/pre_install

# 挂载前检查文件系统
uci set fstab.@global[0].check_fs=1
# 关闭内网ipv6分配
uci del network.globals.ula_prefix
# 数据包引导负载均衡
uci set network.globals.packet_steering='2'
# irq
uci set irqbalance.irqbalance.enabled='1'
# dns
uci del dhcp.cfg01411c.dns_redirect
uci del dhcp.cfg01411c.nonwildcard
uci del dhcp.cfg01411c.noresolv
uci del dhcp.cfg01411c.boguspriv
uci del dhcp.cfg01411c.filterwin2k
uci del dhcp.cfg01411c.filter_aaaa
uci del dhcp.cfg01411c.filter_a
uci add_list dhcp.cfg01411c.notinterface='wan'
uci add_list dhcp.cfg01411c.notinterface='wan6'
uci set dhcp.cfg01411c.port='6666'
uci del AdGuardHome.AdGuardHome.upxflag
uci set AdGuardHome.AdGuardHome.core_version='latest'
uci set AdGuardHome.AdGuardHome.redirect='exchange'
uci set AdGuardHome.AdGuardHome.update_url='https://mirror.ghproxy.com/https://github.com/AdguardTeam/AdGuardHome/releases/download/${Cloud_Version}/AdGuardHome_linux_${Arch}.tar.gz'
uci set AdGuardHome.AdGuardHome.enabled='1'
# lan接口
uci del dhcp.lan.ra
uci del dhcp.lan.ra_slaac
uci del dhcp.lan.ra_flags
uci del dhcp.lan.max_preferred_lifetime
uci del dhcp.lan.max_valid_lifetime
uci add_list network.lan.dns='192.168.2.1'
uci add_list dhcp.lan.dhcp_option='6,192.168.2.1,192.168.2.1'
# wan 接口
uci set network.wan.hostname='*'
uci set network.wan.peerdns='0'
uci add_list network.wan.dns='192.168.2.1'

# cpufreq
uci set cpufreq.cpufreq.minfreq0='408000'
uci set cpufreq.cpufreq.maxfreq0='1608000'

# led
uci add system led # =cfg068bba
uci set system.@led[-1].name='SYS'
uci set system.@led[-1].sysfs='red:status'
uci set system.@led[-1].trigger='heartbeat'
uci del system.led_lan.dev
uci del system.led_lan.mode
uci set system.led_lan.trigger='none'
uci set system.led_lan.default='0'
uci set system.led_wan.trigger='none'
uci set system.led_wan.default='0'
uci del system.led_wan.dev
uci del system.led_wan.mode

# tailscale
uci add network device # =cfg0c0f15
uci set network.@device[-1].name='tailscale0'
uci set network.tailscale=interface
uci set network.tailscale.proto='static'
uci set network.tailscale.device='tailscale0'
uci add_list network.tailscale.ipaddr='100.123.0.1/32'
uci set network.tailscale.gateway='192.168.2.1'
uci add_list network.tailscale.dns='192.168.2.1'
uci add firewall zone # =cfg11dc81
uci set firewall.@zone[-1].name='tailscale'
uci set firewall.@zone[-1].input='ACCEPT'
uci set firewall.@zone[-1].output='ACCEPT'
uci set firewall.@zone[-1].forward='ACCEPT'
uci add_list firewall.@zone[-1].device='tailscale0'
uci set firewall.@zone[-1].masq_allow_invalid='1'
uci set firewall.@zone[-1].auto_helper='0'
uci add_list firewall.@zone[-1].network='tailscale'
uci add firewall forwarding # =cfg12ad58
uci set firewall.@forwarding[-1].src='tailscale'
uci set firewall.@forwarding[-1].dest='docker'
uci add firewall forwarding # =cfg13ad58
uci set firewall.@forwarding[-1].src='tailscale'
uci set firewall.@forwarding[-1].dest='lan'
uci add firewall forwarding # =cfg14ad58
uci set firewall.@forwarding[-1].src='tailscale'
uci set firewall.@forwarding[-1].dest='wan'
uci add firewall forwarding # =cfg15ad58
uci set firewall.@forwarding[-1].src='lan'
uci set firewall.@forwarding[-1].dest='tailscale'
uci add firewall forwarding # =cfg16ad58
uci set firewall.@forwarding[-1].src='wan'
uci set firewall.@forwarding[-1].dest='tailscale'
uci set firewall.cfg01e63d.synflood_protect='1'
uci set firewall.cfg01e63d.input='ACCEPT'
uci set firewall.cfg01e63d.forward='ACCEPT'
uci set firewall.cfg03dc81.forward='ACCEPT'
uci add firewall rule # =cfg1592bd
uci set firewall.@rule[-1].name='Tailscale'
uci set firewall.@rule[-1].src_port='61412'
uci set firewall.@rule[-1].dest='*'
uci set firewall.@rule[-1].target='ACCEPT'
uci add firewall rule # =cfg1692bd
uci set firewall.@rule[-1].name='Tailscale2'
uci set firewall.@rule[-1].src='*'
uci set firewall.@rule[-1].dest='*'
uci set firewall.@rule[-1].target='ACCEPT'
uci add firewall rule # =cfg1792bd
uci set firewall.@rule[-1].name='Tailscale3'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].dest_port='61412'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.cfg1692bd.src_port='61412'
uci reorder firewall.@rule[-1]=21
uci del firewall.cfg1692bd.src_port
uci set firewall.cfg1692bd.dest_port='61412'
uci add firewall rule # =cfg1892bd
uci set firewall.@rule[-1].name='Tailscale4'
uci set firewall.@rule[-1].src='*'
uci set firewall.@rule[-1].src_port='61412'
uci set firewall.@rule[-1].dest='*'
uci set firewall.@rule[-1].target='ACCEPT'
uci reorder firewall.@rule[-1]=22

# 系统
uci set system.cfg01e48a.log_proto='udp'
uci set system.cfg01e48a.conloglevel='8'
uci set system.cfg01e48a.cronloglevel='5'
uci set system.cfg01e48a.zram_comp_algo='lz4'
uci set system.ntp.enable_server='1'
uci set system.ntp.interface='lan'
# samba
# smbpasswd -a root
uci set samba4.cfg010f89.interface='lan'
uci set samba4.cfg010f89.enable_extra_tuning='1'
uci add samba4 sambashare # =cfg02e23c
uci set samba4.@sambashare[-1].name='root'
uci set samba4.@sambashare[-1].path='/'
uci set samba4.@sambashare[-1].read_only='no'
uci set samba4.@sambashare[-1].users='root'
uci set samba4.@sambashare[-1].guest_ok='yes'
uci set samba4.@sambashare[-1].create_mask='0666'
uci set samba4.@sambashare[-1].dir_mask='0777'

# UPUN
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci del upnpd.config.secure_mode
uci del upnpd.config.log_output
uci set upnpd.config.enabled='1'
uci set upnpd.config.use_stun='1'
uci set upnpd.config.stun_host='stun.miwifi.com'

# UA3F
uci set ua3f.main.ua='Ftn67-sdbv'
uci set ua3f.main.log_level='fatal'
uci set ua3f.enabled.enabled='1'

# Uhttpd 删除当前监听443端口的配置
uci del uhttpd.main.listen_https
uci del uhttpd.main.lua_prefix
uci set uhttpd.main.lua_prefix='/cgi-bin/luci=/usr/lib/lua/luci/sgi/uhttpd.lua'
uci set uhttpd.defaults.bits='1024'
# nginx 禁用https
# uci del nginx._redirect2ssl
# uci delete nginx.@server[0].listen
# 添加新的监听80端口的配置
# uci add_list nginx.@server[0].listen='80 default_server'
# uci add_list nginx.@server[0].listen='[::]:80 default_server'
uci commit
/etc/init.d/dnsmasq restart
/etc/init.d/cpufreq restart
/etc/init.d/nginx restart

# 禁用服务
/etc/init.d/tailscale stop
/etc/init.d/tailscale disable
/etc/init.d/dockerd stop
/etc/init.d/dockerd disable
/etc/init.d/dockerman stop
/etc/init.d/dockerman disable
/etc/init.d/wechatpush stop
/etc/init.d/wechatpush disable
/etc/init.d/wpad disable
/etc/init.d/sqm disable
/etc/init.d/avahi-daemon disable
/etc/init.d/qbittorrent disable

exit 0
