--- package/add/ua4f/Makefile	2025-09-18 15:31:19.974815978 +0800
+++ package/add/ua4f/Makefile	2025-09-18 15:30:37.433363611 +0800
@@ -7,6 +7,8 @@
 PKG_LICENSE:=AGPL-3.0-or-later
 PKG_LICENSE_FILES:=LICENSE.md
 
+PKG_BUILD_FLAGS:=no-lto
+
 HOST_BUILD_DEPENDS:=rust/host
 
 include $(INCLUDE_DIR)/package.mk
