#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=80

autocore() {
    rfc=4096
    threads="$(grep -c "processor" "/proc/cpuinfo")"

    sysctl -w net.core.rps_sock_flow_entries="$((rfc * threads))"

    for fileRps in /sys/class/net/eth*/queues/rx-*/rps_cpus; do
        echo "$threads" >"$fileRps"
    done

    for fileRfc in /sys/class/net/eth*/queues/rx-*/rps_flow_cnt; do
        echo "$rfc" >"$fileRfc"
    done

    uci set network.@globals[0].packet_steering="2"
    uci commit network

    for i in $(ip address | awk -F ': ' '/eth[0-9]+/ {print $2}' | grep -v '@' | xargs); do
        # echo "开启接口特性 on $eth"
        ethtool -K "$i" rx-checksum on
        ethtool -K "$i" tx-checksum-ip-generic on || (
            ethtool -K "$i" tx-checksum-ipv4 on
            ethtool -K "$i" tx-checksum-ipv6 on
        )
        ethtool -K "$i" tx-scatter-gather on
        ethtool -K "$i" gso on
        ethtool -K "$i" gro on
        ethtool -K "$i" lro on
        ethtool -K "$i" tso on
        ethtool -K "$i" ufo on
        ethtool -K "$i" rx-gro-list on
        ethtool -K "$i" rx-udp-gro-forwarding on
        ethtool -K "$i" tcp-segmentation-offload on
        ethtool -K "$i" tx-nocache-copy off

        if ethtool -i "$i" | grep -q "driver: igc"; then
            ethtool -G "$i" rx "$(ethtool -g "$i" | awk '/^RX:/ {print $2; exit}')"
            ethtool -G "$i" tx "$(ethtool -g "$i" | awk '/^TX:/ {print $2; exit}')"
        fi
    done
} >"/dev/null" 2>&1

mod_qdisc() {
    # 修改 eth1（wan） 接口的队列调度器
    tc qdisc replace dev eth1 root fq_codel
    # tc qdisc replace dev eth1 root cake bandwidth 20Mbit internet diffserv3

    # 修改 eth0 (lan) 接口的队列调度器
    tc qdisc replace dev eth0 root fq_codel
    # tc qdisc replace dev eth0 root cake bandwidth 100Mbit internet diffserv3

    # 修改 tailscale0 接口的队列调度器
    tc qdisc replace dev tailscale0 root fq_codel
    # tc qdisc replace dev tailscale0 root cake unlimited besteffort internet

    # 修改 utun 接口的队列调度器
    tc qdisc replace dev utun root fq_codel
    # tc qdisc replace dev utun root cake unlimited besteffort internet

} >"/dev/null" 2>&1

queue_cores="0 1 2 3"
start() {
    logger "开始优化"

    bash /etc/xyw/login.sh

    autocore

    mod_qdisc

    nft delete table ip filter
    nft delete table ip nat
    nft delete table ip6 filter
    nft delete table ip6 nat
    iptables -F
    iptables -X
    iptables -Z

    wait
    sync
    echo 1 >/proc/sys/vm/drop_caches
    /etc/init.d/zram compact
}
