--- package/feeds/packages/libffi/Makefile	2025-09-17 18:03:01.962920605 +0800
+++ package/feeds/packages/libffi/Makefile	2025-09-17 18:11:33.637739049 +0800
@@ -75,8 +75,10 @@
 	$(CP) \
 		$(PKG_INSTALL_DIR)/usr/include/*.h \
 		$(1)/usr/include/
+	
+	cd $(wrtdir)/build_dir/target-aarch64_cortex-a53_musl/libffi-$(PKG_VERSION)/aarch64-openwrt-linux-gnu && ./config.status fficonfig.h
 	$(CP) \
-		$(PKG_BUILD_DIR)/$(GNU_TARGET_NAME)*/fficonfig.h \
+		$(wrtdir)/build_dir/target-aarch64_cortex-a53_musl/libffi-$(PKG_VERSION)/aarch64-openwrt-linux-gnu/fficonfig.h \
 		$(1)/usr/include/
 endef
 
