--- a/package/feeds/packages/libffi/Makefile	2025-09-17 18:03:01.962920605 +0800
+++ b/package/feeds/packages/libffi/Makefile	2025-09-17 18:07:51.235501992 +0800
@@ -75,8 +75,9 @@
 	$(CP) \
 		$(PKG_INSTALL_DIR)/usr/include/*.h \
 		$(1)/usr/include/
+	
 	$(CP) \
-		$(PKG_BUILD_DIR)/$(GNU_TARGET_NAME)*/fficonfig.h \
+		$(wrtdir)/build_dir/target-aarch64_cortex-a53_musl/libffi-$(PKG_VERSION)/aarch64-openwrt-linux-gnu/fficonfig.h \
 		$(1)/usr/include/
 endef
 
