--- package/feeds/packages/rust/Makefile	2025-09-23 16:06:04.292310957 +0800
+++ package/feeds/packages/rust/Makefile	2025-09-29 17:17:52.841563670 +0800
@@ -75,7 +75,7 @@
 	--release-channel=stable \
 	--enable-cargo-native-static \
 	--bootstrap-cache-path=$(DL_DIR)/rustc \
-	--set=llvm.download-ci-llvm=true \
+	--set=llvm.download-ci-llvm="if-unchanged" \
 	$(TARGET_CONFIGURE_ARGS)
 
 define Host/Uninstall
