--- feeds/packages/utils/docker/Makefile	2025-09-16 13:14:04.000000000 +0800
+++ feeds/packages/utils/docker/Makefile	2025-09-19 09:29:56.187059513 +0800
@@ -64,6 +64,11 @@
 		GITCOMMIT=$(PKG_GIT_SHORT_COMMIT) \
 		VERSION=$(PKG_VERSION) \
 		./scripts/build/binary; \
+		# 兼容自定义输出路径（例如 R2S/docker-linux-$(GOARCH)）
+		if [ -f R2S/docker-linux-$(GOARCH) ]; then \
+			mkdir -p build; \
+			cp R2S/docker-linux-$(GOARCH) build/docker; \
+		fi \
 	)
 endef
 
