name: LynnOS-build

on:
  workflow_dispatch:
    inputs:
      target:
        description: "选择编译目标"
        default: "r2s"
        type: choice
        required: true
        options:
          - r2s
      build:
        description: "编译固件"
        default: true
        type: boolean
        required: true
      skip_max_space:
        description: "跳过最大化储存空间"
        default: false
        type: boolean
        required: false
      save_ccache:
        description: "保存 ccache（可能很大）"
        default: true
        type: boolean
        required: false
      clean_cache:
        description: "清理编译缓存"
        default: false
        type: boolean
        required: false
      skip_saving_cache:
        description: "这次不保存缓存"
        default: false
        type: boolean
        required: false
      needssh:
        description: "需要 SSH 连接调试"
        default: false
        type: boolean
        required: false

defaults:
  run:
    shell: bash

jobs:
  Build:
    runs-on: "ubuntu-24.04"

    env:
      DEBIAN_FRONTEND: noninteractive # 无交互
      immortalwrt_branch: "master" # TODO: 以后改成输入参数
      workdir_out: ""
      target: ""

    steps:
      - if: github.event.inputs.build == 'true' && github.event.inputs.skip_max_space == 'false'
        name: 准备可用空间
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"
          remove-large-packages: "true"
          remove-cached-tools: "true"
          remove-swapfile: "true"

      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 准备容器 （init-out.sh）
        run: bash prepare/init-out.sh

      - name: 接收环境变量
        run: |
          d '
            . set_env target "${{ github.event.inputs.target }}"
            . set_env immortalwrt_branch "${{ env.immortalwrt_branch }}"
            . set_env targetdir "${lynndir}/target/${target}"
          '

      - name: 准备环境 （init-in.sh）
        run: d "cd ${lynndir} && bash prepare/init-in.sh"

      - name: 准备编译目标设备 （prepare.sh）
        run: |
          d "
            cd ${wrtdir}
            bash ${lynndir}/target/${target}/prepare.sh
            p "追加配置"
            cat .config_pending | tee -a .config
            p "展开配置"
            make defconfig -j$(($(nproc) + 1))
          "

      - name: 恢复缓存
        id: cache-restore
        uses: stupidloud/cachewrtbuild@main
        with:
          prefix: "${{ env.workdir_out }}/immortalwrt"
          mixkey: "${{ env.target }}"
          ccache: "${{ github.event.inputs.save_ccache }}"
          toolchain: "true"
          clean: "${{ github.event.inputs.clean_cache }}"
          skip_saving: "${{ github.event.inputs.skip_saving_cache }}"

      - name: 压缩编译目录
        run: |
          if [ '${{ steps.cache-restore.outputs.hit }}' == '1' ]; then
            p "缓存命中"
          else
            p "未命中缓存"
          fi

          d '
            cd ${workdir}
            cp -r ${lynndir} ${wrtdir}/
            tar -cf --exclude="$(basename ${wrtdir})/.ccache" - $(basename ${wrtdir})/ | zstd -19 -T0 > wrt_end.tar.zst
            # 效率-3 均衡-15 适度-16 最大-19 极限--ultra -22
            rm -rf ${wrtdir}/$(basename ${lynndir})
          '

      - name: 上传编译目录
        uses: actions/upload-artifact@main
        with:
          name: wrt_end.tar.zst
          path: "${{ env.workdir_out }}/wrt_end.tar.zst"
          compression-level: 0

      - if: github.event.inputs.build == 'true'
        name: 开始编译：${{ env.target }}
        run: |
          d '
            cd ${wrtdir}
            p "开始编译"
            make download -j$(($(nproc) + 1)) -k # 避免部分下载失败导致终止
            make world -j$(($(nproc) + 1))
            if [ $? -ne 0 ]; then
              p "！！编译失败，进行单线程详细日志编译"
              make download -j$(($(nproc) + 1)) -k
              make world V=s -j1
              if [ $? -ne 0 ]; then
                p "！！单线程编译依然失败，结束"
                exit 1
              else
                p "单线程编译成功"
                . set_env build_success "true"
              fi
            else
              p "编译成功"
              . set_env build_success "true"
            fi

            p "打包所有产物"
            tar -cf - bin/ | zstd -19 -T0 > "${workdir}/bin_${target}.tar.zst"
            p "打包软件包"
            tar -C bin/ -cf - packages/ | zstd -19 -T0 > "${workdir}/packages_${target}.tar.zst"
          '
          p "打印剩余空间"
          df -h

      - if: github.event.inputs.build == 'true'
        name: 上传产物文件夹
        uses: actions/upload-artifact@main
        with:
          name: firmware
          path: "${{ env.workdir_out }}/bin_${{ env.target }}.tar.zst"
          compression-level: 0
          if-no-files-found: error

      - if: always() && github.event.inputs.needssh == 'true'
        name: SSH 临时调试
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 240
