name: R2S-LynnOS

on:
  workflow_dispatch:
    inputs:
      build:
        description: "进行编译"
        default: true
        type: boolean
        required: true

defaults:
  run:
    shell: bash

jobs:
  Build:
    runs-on: "ubuntu-24.04"

    steps:
      # - name: Maximize build space
      #   uses: AdityaGarg8/remove-unwanted-software@v5
      #   with:
      #     remove-dotnet: "true"
      #     remove-android: "true"
      #     remove-haskell: "true"
      #     remove-codeql: "true"
      #     remove-docker-images: "true"
      #     remove-large-packages: "true"
      #     remove-cached-tools: "true"
      #     remove-swapfile: "true"

      - run: |
          df -h
          sudo mkdir /mnt/ciwork && sudo chown -R runner:runner /mnt/ciwork
          docker pull cachyos/cachyos-v3
          docker run -d --name cachyos --user $(id -u):$(id -g) -v /mnt/ciwork:/ciwork -w /ciwork cachyos/cachyos-v3 tail -f /dev/null

          function de() { docker exec cachyos bash -c "$1"; }
          function der() { docker exec -u root cachyos bash -c "$1"; }

          # de 和 der 是在Arch容器内执行命令的别名
          echo "Updating package database..."
          der pacman -Syyu --noconfirm
          echo "Installing required packages..."
          der pacman -Syu --needed --noconfirm base-devel asciidoc autoconf automake binutils bison \
            bzip2 ccache clang cmake cpio curl dtc eclipse-ecj fastjar flex gawk gettext \
            gcc-multilib git gnutls gperf haveged help2man intltool lib32-gcc-libs lib32-glibc \
            libelf glib2 gmp libtool libmpc mpfr ncurses python python-pip python-ply \
            python-docutils python-pyelftools qemu-img re2c rsync scons squashfs-tools \
            subversion swig texinfo uglify-js upx unzip vim wget xmlto xxd zlib zstd 7zip \
            paru
          de paru --noconfirm -S ack antlr3
          echo "All required packages installed."

          de <<EOF
          git clone ${{ github.repositoryUrl }} /ciwork/LynnOS
          cd /ciwork/LynnOS && git checkout ${{ github.sha }}
          echo "Starting build..."
          EOF

          
      - if: ${{ failure() }}
        name: Setup tmate session
        uses: mxschmitt/action-tmate@v3