name: R2S-LynnOS

on:
  # schedule:
  #   - cron: 00 17 * * 5
  # 北京时间(UTC+8) 星期六早上 1:00
  # push:
  #   branches:
  #     - "main"
  #   paths:
  #     - "script/01_prepare_package.sh"
  #     - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "选择分支"
        required: true
        default: "openwrt-23.05"
        type: string
      build:
        description: "进行编译"
        type: boolean
        default: true
        required: true

jobs:
  Build:
    runs-on: "ubuntu-22.04"

    env:
      TAG: R2s
      CURRENT_TIME: "2024"
      needBuild: false
      buildSuccess: none
      TERM: xterm
      # 无交互
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: 写入环境变量
        run: |
          if [ "${{ inputs.build }}" = "true" ] || [ "${{ github.event.schedule }}" ]; then
            echo "needBuild=true" >> $GITHUB_ENV
          else
            echo "needBuild=false" >> $GITHUB_ENV
          fi

      - name: 最大化储存空间
        uses: easimon/maximize-build-space@master
        if: env.needBuild == true
        with:
          swap-size-mb: 1
          temp-reserve-mb: 200
          root-reserve-mb: 5000
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"
          remove-docker-images: "true"

      - name: 克隆代码
        uses: actions/checkout@main
        with:
          ref: main
          fetch-depth: 1

      - name: 准备编译环境
        env:
          # 依赖
          DEPENDENCY: ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
        # -E 表示传递环境变量
        run: |
          echo "开始更新"
          {
            sudo swapoff -a &
            sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc &
            sudo rm -rf /etc/apt/sources.list.d/*
            /bin/bash -c "$(curl -sL https://git.io/vokNn)"
            sudo -E cp -rf ./script/apt-fast.conf /etc
            sudo -E apt-fast -qq update -y
            sudo -E apt-fast -qq dist-upgrade -y
          } >/dev/null
          wait
          echo "更新完成，开始安装依赖"
          { 
            sudo -E apt-fast -qq install -y $DEPENDENCY
            sudo -E apt-fast -qq autoremove --purge -y
            sudo -E apt-fast -qq clean -y
            sudo -E git config --global user.name 'GitHub Actions'
            sudo -E git config --global user.email 'noreply@github.com'
            sudo -E git config --global core.abbrev auto
          } >/dev/null
          wait
          git clone -b ${{ inputs.build }} --depth 1 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt.git ./ImmortalWrt >/dev/null

      - name: 运行自定义脚本
        run: |
          pushd ./ImmortalWrt
          cp -r ../script/. ./
          bash 01_prepare_package.sh
          bash 02_target_${{ env.TAG }}.sh
          bash 03_create_acl_for_luci.sh -a
          make defconfig
          wait && popd

          if [ "${{ env.needBuild }}" = "true" ]; then
            tar -cf - ./ImmortalWrt/ | zstd -8 -T0 -o ./ImmortalWrt-End.tar.zst
          else
            tar -cf - ./ImmortalWrt/ | zstd -19 -T0 -o ./ImmortalWrt-End.tar.zst
          fi

          sudo df -h

      - name: 恢复缓存
        if: env.needBuild == true
        uses: HiGarfield/cachewrtbuild@main
        with:
          ccache: true
          toolchain: true
          skip: true
          mixkey: "${{ env.TAG }}"
          prefix: ${{ github.workspace }}/ImmortalWrt

      - name: 编译 LynnOS
        if: env.needBuild == true
        id: build
        continue-on-error: true
        working-directory: ./ImmortalWrt
        env:
          IGNORE_ERRORS: 1
        run: |
          make download -j32

          if make -j$(($(nproc) + 1)); then
            echo "buildSuccess=true" >> $GITHUB_ENV
          else
            echo "buildSuccess=false" >> $GITHUB_ENV
          fi

      - name: debug 详细日志编译
        if: env.buildSuccess == false
        continue-on-error: true
        working-directory: ./ImmortalWrt
        run: |
          make -j1 V=s

      - name: 编译完成，打包镜像
        if: env.buildSuccess == true
        working-directory: ./ImmortalWrt/bin/targets/rockchip/armv8/
        run: |
          ## ./ImmortalWrt/bin/targets/rockchip/armv8/
          tar -cf - ./packages --remove-files | zstd -19 -T0 -o ./packages.tar.zst
          cd .. 

          ## ./ImmortalWrt/bin/targets/rockchip/
          tar -cf - ./armv8 | zstd -19 -T0 -o ./output.tar.zst
          cp -rf ./output.tar.zst ./armv8


          echo "CURRENT_TIME=$(date -u +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

          df -h

      - name: 上传至 artifact
        uses: actions/upload-artifact@main
        continue-on-error: true
        with:
          name: Output
          if-no-files-found: warn
          compression-level: 0
          path: |
            ImmortalWrt-End.tar.zst
            ImmortalWrt/bin/targets/rockchip/armv8/output.tar.zst

      - name: 创建发行版
        if: env.buildSuccess == true
        uses: ncipollo/release-action@main
        continue-on-error: true
        with:
          name: LynnOS-${{ env.TAG }}-${{ env.CURRENT_TIME }}
          allowUpdates: true
          replacesArtifacts: true
          artifactErrorsFailBuild: false
          commit: main
          tag: "Success-${{ env.TAG }}-${{ env.CURRENT_TIME }}"
          body: "${{ env.CURRENT_TIME }} 自动发布 LynnOS-${{ env.TAG }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ImmortalWrt/bin/targets/rockchip/armv8/*
